### PR TITLE
Feature kawan product details

### PR DESCRIPTION
**Pull request by Kawium**
Feature kawan product details for mobile #8

### CODE REVIEW

**Review by Vacannot — CHANGES_REQUESTED** [review]
Remove changes to LogInPage as most likely all of us are going to have added our test components there.

Rename back the "Pages" to "pages" with lowercase p

**Review by Vacannot — CHANGES_REQUESTED** [review]
move image from public into assets folder, i'll show you how to handle them later

**Review by fiababiakandersson — APPROVED** [review]
👯

**Review by Vacannot — APPROVED** [review]
I made minor changes to ProductDetails by removing the css and instead putting it in MUI components, works the exact same!

**Pull request merged**
