### PR TITLE
Feature simon accept decline response

### PR DESCRIPTION
**Pull request by Vacannot**
Accept & Decline responses and StartPage for desktop

### CODE REVIEW

**Comment by Vacannot** [comment]
There are still bugs with the colors on hover on the different buttons but focusing towards MVP and not the details at the moment

**Review by Kawium — APPROVED** [review]
you could add overflow hidden so it removes scrolling in the page but otherwise everything looks good!

**Review by Kawium — APPROVED** [review]
looks good!

**Review by maxAndersson — APPROVED** [review]

**Review by fiababiakandersson — APPROVED** [review]
👯

**Pull request merged**
